#!/usr/bin/env python3

import os
import sys
if sys.version_info.major < 3:
    import ci_tools as tools
else:
    from ci_scripts import ci_tools as tools


def _get_test_command()-> str:
    prefix = "travis_wait 30 " if current_test_suite == "centos7" else ""
    cmd = "{0}pytest -v -rs -k {1}".format(prefix, current_test_suite)
    return cmd


if __name__ == '__main__':
    current_test_suite = os.getenv("TEST_TAG")
    cmd = _get_test_command()
    print("Running: {0}".format(cmd))
    tools.run_console_command(cmd)
    print("Done.")
